### ISSUE TITLE
Bleak Exception on macOS BigSur (M1)

### ISSUE THREAD

**Issue by omkarkarande** [TapWithUs/tap-python-sdk#10]
Running the provided [example file](https://github.com/TapWithUs/tap-python-sdk/blob/master/examples/example_macos.py) on an M1 mac running Big Sur, I am getting the following exception: 

```
Traceback (most recent call last):
  File "/Users/omi/Workspaces/TAPPlayground/example.py", line 1, in <module>
    from tapsdk import TapSDK, TapInputMode
  File "/opt/homebrew/lib/python3.9/site-packages/tapsdk/__init__.py", line 10, in <module>
    from tapsdk.backends.macos.TapSDK import TapMacSDK as TapSDK
  File "/opt/homebrew/lib/python3.9/site-packages/tapsdk/backends/macos/TapSDK.py", line 8, in <module>
    from bleak import BleakClient
  File "/opt/homebrew/lib/python3.9/site-packages/bleak/__init__.py", line 54, in <module>
    raise BleakError("Bleak requires the CoreBluetooth Framework")
bleak.exc.BleakError: Bleak requires the CoreBluetooth Framework
```

I looked over at bleak's issues to see if this was a problem with their support for BigSur and found this [thread](https://github.com/hbldh/bleak/issues/365). Tried installing a higher version of bleak(0.10.0) than what is required by tap (0.5.1), but as expected ran into conflicts as it looks like that version is not backwards compatible. 

```
Traceback (most recent call last):
  File "/Users/omi/Workspaces/TAPPlayground/example.py", line 1, in <module>
    from tapsdk import TapSDK, TapInputMode
  File "/opt/homebrew/lib/python3.9/site-packages/tapsdk/__init__.py", line 10, in <module>
    from tapsdk.backends.macos.TapSDK import TapMacSDK as TapSDK
  File "/opt/homebrew/lib/python3.9/site-packages/tapsdk/backends/macos/TapSDK.py", line 10, in <module>
    from bleak.backends.corebluetooth.discovery import discover
ModuleNotFoundError: No module named 'bleak.backends.corebluetooth.discovery'
```

**Comment by omkarkarande** [comment]
Using bleak==0.9.1 as recommended in that thread yields this

```
Traceback (most recent call last):
  File "/Users/omi/Workspaces/TAPPlayground/example.py", line 1, in <module>
    from tapsdk import TapSDK, TapInputMode
  File "/opt/homebrew/lib/python3.9/site-packages/tapsdk/__init__.py", line 10, in <module>
    from tapsdk.backends.macos.TapSDK import TapMacSDK as TapSDK
  File "/opt/homebrew/lib/python3.9/site-packages/tapsdk/backends/macos/TapSDK.py", line 11, in <module>
    from bleak.backends.corebluetooth import CBAPP as cbapp
ImportError: cannot import name 'CBAPP' from 'bleak.backends.corebluetooth' (/opt/homebrew/lib/python3.9/site-packages/bleak/backends/corebluetooth/__init__.py)

```

**Comment by KatMab** [comment]
I am getting the same error with bleak requiring the CoreBluetooth Framework using the macOS Tap-strapSDK. Have you had any progress fixing this issue?

**Comment by omkarkarande** [comment]
Na. I dug into this a bit but hit a wall. Ended up using a spare raspberry pi for tap development. 

The linux environment worked well without any hiccups.

**Comment by KatMab** [comment]
So I was able to get rid of the first error by simply having "import CoreBluetooth" before bleak is imported, even though the script itself doesn't actually use CoreBlutooth.

**Comment by ilouzl** [comment]
@omkarkarande 
The sdk was updated to support the latest bleak release (0.12.1). 
Please take a look at [release 0.5.0](https://github.com/TapWithUs/tap-python-sdk/releases/tag/0.5.0) and see if it resolves your issue.

**Comment by ilouzl** [comment]
closing due to inactivity
