### ISSUE TITLE
bluez-tools packaged required on linux

### ISSUE THREAD

**Issue by SolidEva** [TapWithUs/tap-python-sdk#7]
the following error is created if the `bluez-tools` package is missing

```Traceback (most recent call last):
  File "./readtap.py", line 19, in <module>
    main()
  File "./readtap.py", line 11, in main
    tap_device = TapSDK()
  File "/home/solidhal/.local/lib/python3.8/site-packages/tapsdk/backends/linux/TapSDK.py", l
    self.address = address if address else self.get_mac_addr()
  File "/home/solidhal/.local/lib/python3.8/site-packages/tapsdk/backends/linux/TapSDK.py", l
    raise e
  File "/home/solidhal/.local/lib/python3.8/site-packages/tapsdk/backends/linux/TapSDK.py", l
    with Popen(["bt-device", "--list"], stdout=PIPE, text=True) as btdevice_process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bt-device'
```

sudo apt-get install bluez-tools

fixes this

**Comment by ilouzl** [comment]
Have you had libbluetooth-dev installed when you got that error?

**Comment by SolidEva** [comment]
yep, and actually the comment https://github.com/TapWithUs/tap-python-sdk/pull/3#issuecomment-660524302 on the PR that added support mentions the requirement of the bluez package
